# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KixLUWYpxhyYDa-_mvBP8rH1vdPlPgUN
"""

#3
def soma(x,y,z):
  return x+y+z

print(soma(1,1,1))

#4
def sinal(x):
    if x>0:
      return 'P' 
    else:
      return 'N'
print(sinal(0))

